### PR TITLE
Studies call

### PR DESCRIPTION
**Pull request by reynoldtan**
Study is defined as a phenotyping experiment conducted at a single geographic location. One Trial can have multiple studies conducted (e.g. multi location international trials).

Note that dates should be provided in extended ISO 8601 format (for example, "YYYY-MM-DD").

https://brapi.docs.apiary.io/#reference/study

## Metadata

- [x] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [ ]
 
Documentation:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description

This PR covers calls under Study namely:
brapi/v1/observationlevels 
brapi/v1/seasons
brapi/v1/studytypes
brapi/v1/studies
brapi/v1/search/studies

Note: Only studies and search/studies are implemented, other calls are placeholder for when method to fetch relevant information is established but call directory, class files, call response fields and parameters are all defined except the query used to fetch relevant information.

## Testing?

- [ ] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

To test call:
```
OBSERVATION LEVELS
// Will return an empty result.
Call parameters: page and pageSize
Example:
host/web-services/brapi/v1/observationlevels 
host/web-services/brapi/v1/observationlevels?page=2&pageSize=10 
```
```
SEASONS
// Will return an empty result.
Call parameters: seasonDibId, season, page and pageSize
Example:
host/web-services/brapi/v1/seasons
host/web-services/brapi/v1/seasons?seasonDbId=123
```
```
STUDYTYPES
// Will return an empty result.
Call parameters: studyTypeDibId, page and pageSize
Example:
host/web-services/brapi/v1/studytypes
host/web-services/brapi/v1/studytypeDbId=123&page=1
```
```
STUDIES
Call parameters: commonCropName, programDbId, locationDbId, trialDbId, sortBy [commonCropName, name, studyName], sortOrder, page and pageSize.
Example:
host/web-services/brapi/v1/studies
host/web-services/brapi/v1/studies?commonCropName=Lens
host/web-services/brapi/v1/studies?commonCropName=Lens&programDbId=123
host/web-services/brapi/v1/studies?trialDbId=123&sortBy=studyName&sortOrder=asc
```
```
SEARCH
Call parameters: commonCropNames, programDbIds, locationDbIds, trialDbIds, sortBy [commonCropName, name, studyName], sortOrder, page and pageSize.

POST a search request

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "host/web-services/brapi/v1/search/studies"); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);
curl_setopt($ch, CURLOPT_POST, TRUE);

// Parameter
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"commonCropNames\" : [\"Lens\"], \"programDbIds\":[588, 589]}");

curl_setopt($ch, CURLOPT_HTTPHEADER, ["Content-Type: application/json"]);
$response = curl_exec($ch);
curl_close($ch);
var_dump($response);

GET response of a search request.
host/web-services/brapi/v1/search/studies?searchResultDbId=hash **code returned by POST request**
```

Note: BrAPI paging starts at 0.

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Not providing sane results for all records on a KnowPulse clone. it looks like the record results are offset?

Screen Shot 2020-08-05 at 12 49 15 PM
Screen Shot 2020-08-05 at 12 49 06 PM

**Comment by reynoldtan** [comment]
Revised studies call to reference chado.phenotype and chado.phenotypeprop table instead of Raw Phenotypes.

**Review by laceysanderson — CHANGES_REQUESTED** [review]
The results are still offset
Screen Shot 2020-08-20 at 9 38 49 AM

Confirmation I have the updated commits and cleared my cache:
Screen Shot 2020-08-20 at 9 42 18 AM

**Comment by reynoldtan** [comment]
Revised studies call and with test data generated by support module, will produce response below

Screen Shot 2020-09-22 at 9 33 38 AM (2)


**Please use the updated core class**

**Review by laceysanderson — APPROVED** [review]
Works 👍 
Tested both the listing and the search with test data provided by the test module.

**Pull request merged**
