### PR TITLE
Creates unit test for ontologies call

### PR DESCRIPTION
**Pull request by reynoldtan**
Creates unit test for ontologies call

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
Code Changes: none needed
Check in the Browser on Test Data:
 - Structure matches Apiary ✅
 - Data correct: I'm not sure it is... shouldn't it be the cv not the cvterm? ❓ 
 - Returns results using test data ✅
 - Check parameters ✅

Test Review:
 - Tests all parameters ✅
 - Includes correct data structure and data types based on Apiary ✅

Tests Pass ✅

**Comment by reynoldtan** [comment]
Data correct: I'm not sure it is... shouldn't it be the cv not the cvterm?
Could you please expand on this?

**Comment by laceysanderson** [comment]
An ontology is a group of terms (usually with hierarchy) which can be used to categorize data. Whereas, a controlled vocabulary (CV) is a collection of terms without hierarchy, properties, definitions, etc. For more regarding the [difference between ontologies and controlled vocabularies see this StackOverflow answer](https://stackoverflow.com/a/20200388/4821318). In Chado, a single ontology maps to a record in the cv table.

From the BrAPI Specification:
> Call to retrieve a list of observation variable ontologies available in the system.

From this BrAPI definition, the call should return a list of ontologies (i.e. cv records) whose terms describe observation variables. 

From the BrAPI Specification:
> API to retrieve list and details of observation variables. An observation variable is composed by the unique combination of one Trait, one Method and one Scale.

Thus the call should return a list of ontologies (i.e. cv records) whose terms are either traits, methods or scales (units). Generically, this is any cv whose cvterms appear in the [phenotype table](https://chado.readthedocs.io/en/rtd/_static/schemaspy_integration/phenotype/tables/phenotype.html) (i.e. observable_id, attr_id, cvalue_id, assay_id).

**Comment by reynoldtan** [comment]
Revised ontologies call as described

**Review by laceysanderson — APPROVED** [review]
Code Changes: ✅
Check in the Browser on Test Data:
 - Structure matches Apiary ✅
 - Data correct: ✅
 - Returns results using test data ✅
 - Check parameters ✅

Test Review:
 - Tests all parameters ✅
 - Includes correct data structure and data types based on Apiary ✅

Tests Pass ✅

**Pull request merged**
