### PR TITLE
Creates unit test for samples call

### PR DESCRIPTION
**Pull request by reynoldtan**
Creates unit test for samples call

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Code Changes:
 - missing plateDbId. This should be included even if it's always n/a ❌ 

Check in the Browser:
 - Structure matches Apiary ✅ 
 - Data correct ✅ 
 - Returns results using test data ✅ 
 - Check parameters
     - sampleDbId ✅ 
     - observationUnitDbId ✅ 
     - plateDbId ❌ 
     - germplasmDbId ✅ 
     - 
Test Review:
 - Tests all parameters: missing plateDbId ❌ 
 - Includes correct data structure and data types based on Apiary ✅ 

Tests Pass ✅

**Comment by reynoldtan** [comment]
This call fetches data from the following tables: stock, stockprop, phenotype, cvterm, cv and dbxref table. Please advice which field describes the plateID parameter, if coming from another relation from mentioned, please advice too.

**Comment by laceysanderson** [comment]
The plateDbId would typically be a stockprop.value. However, there is not an example of this in KnowPulse or DivSeek Canada portal and there is no community decided upon cvterm. Thus you can implement this by allowing it to be optional and allowing the type term to be configurable. On quick review of EBI we could use [this term](http://purl.obolibrary.org/obo/NCIT_C50106) as a default 🤷‍♀️

**Comment by reynoldtan** [comment]
Revised samples call - see data map below showing stock, stock prop, phenotype and phenotypeprop. Please note the phenotype entries (4) all have same property. Had there more different property, there would be one item for each in the response.
mapsamples

**Comment by reynoldtan** [comment]
Revised sample call to:
1. Retrieve all stocks, any types (DNA, accession, cultivar etc.)
2. When stock is DNA, fetch phenotype properties
Example: for stock lola, stella, luna, izzy, layla, lulu, ellie, piper, olivia, king, max, owen, ray, ralph, rex, scout, tesla, wyatt, ace and bailey.
3. Not DNA, phenotypes property set to n/a
Example: for stock nala with 1 phenotype but is an accession will have all phenotype prop set to n/a

**Pull request merged**
