### PR TITLE
Revised overall module functionality

### PR DESCRIPTION
**Pull request by reynoldtan**
Please see the documentation in test/ directory to assist you in reviewing this PR. This document is laid out starting with less technical details of the module to technical, code-level specifications. Feel free to skip topics as needed as well as point errors, typos and ambiguous sections.

Also in this directory a code that will create a test environment for you to test many components - configuration, database call, search call etc.

Both of these documents will become part of the module as user guide and for unit test.

Thanks and let me know.

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Overall this PR is looking like a great step forward 😃 The following is the breakdown of my review:
- ⚠️   User Documentation looks great :-) however, it should be in ReadtheDocs format in the doc directory
- ❌  Module still needs a general Readme
- ✅  Module installs as expected with appropriate defaults 
- ✅  Configuration is provided and is easy to change
- ✅  Custom call works as expected
- ✅  Database call works as expected 
- ✅  Search Call works as expected for 1.3
- ⚠️   Test data insertion did not work when copy/pasted -should be replaced with a database seeder
- ✅  Uses the Tripal WS API to list the call alongside other Tripal WS
- ⚠️ **I noticed this module currently has its full set of helper classes to process responses, etc. Are these still being used? If yes, can we use more of the Tripal WS core to reduce any duplication?**

**Key:** ❌ means it must be changed before merge. ⚠️ means it must be changed before release but can be in another PR.

**Review by laceysanderson — APPROVED** [review]
I addressed some of my original comments. Specifically,
- ✅ I populated the README with basic information.
- ✅ Initialized TripalTestSuite testing
- ✅ Added basic test to check installation and config variables.
- ✅ Added Database seeder and removed "deplorable script"
- ✅ Initialized Readthedocs

Now I believe this PR is ready to merge. **However, I still need my question regarding overall structure answered and the DOCX documentation needs to be converted to Readthedocs.**

**Comment by reynoldtan** [comment]
> I noticed this module currently has its full set of helper classes to process responses, etc. Are these still being used? If yes, can we use more of the Tripal WS core to reduce any duplication?

All call types use 2 helper classes namely TripalWebServiceResourceIdentifier.inc and TripalWebServiceResponse.inc. The first class takes care of parsing all information contained in the request URL such as version number, call name, parameters to the call as well as flag if a call is of search type. The other helper class is responsible for transforming response to a required format - JSON in this case, but it can be extended to support other format such as XML and other when need arises.

Based on my code review of Tripal WS core, I observed that the classes operate in a certain way consistent with HYDRA ontology requirements, particularly the way it handles essential areas:

1. **version** - includes both major and minor version number in the request whereas it only requires major version in BraAPI.

2. **parameters** - does not handle query string in the request url but BrAPI allows for parameters passed to a request.

3. **Response result is hypertext values JSON-LD (Linked Data)** - BrAPI response is text only, no markup.

5. **Response field/key** - HYDRA ontology as response keys are hard-coded in the class.

Core classes can be reprogrammed but I feel it will end with one major override code. In addition to this, classes are equipped with auto-loading constructors that would initialize a handful of variables, call a number of methods and inspect certain directory for any implementations, all together are specific to HYDRA and would be unrelated to BrAPI, hence I prepared this two helper classes unique to BrAPI but with flexibility to accommodate other ontologies.

**Comment by laceysanderson** [comment]
> Core classes can be reprogrammed but I feel it will end with one major override code.

Ok, we will move forward with these classes for our Tripal 3 compatible version. However, for Tripal 4 I expect these classes to be gone and core Tripal to be used.

That means this can be merged! Thank you for the work @reynoldtan

**Pull request merged**
