### PR TITLE
BRAPPS - graphical filtering and study comparison

### PR DESCRIPTION
**Pull request by reynoldtan**

### CODE REVIEW

**Comment by reynoldtan** [comment]
Tripal Web Service BrAPI - Implementation of Graphical Filtering and Study Comparison BRAPPS, created by BREEDBASE.

Both BRAPPS operate on BrAPI V1.2 call phenotypes-search.

image

_BRAPPS showing result of sample data provided by tripal_ws_brapi_testdata module_

### **To test:**

1. Clone tripal_ws_brapi module into your Drupal modules/custom directory.
https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi.git

2. Switch branch to **brapps** and enable tripal_ws_brapi module.

3. Configure Tripal WS BrAPI to recognize BrAPI call V1.2 in the configuration page by adding 1.2 (Major version 1 and minor version 2) and setting it as a default for version v1.

**your tripal sites/admin/tripal/extension/tripalwsbrapi/configure/version**

image

4. Both BRAPPS use past and older version Javascript libraries of Bootstrap, JQuery, Datatables and D3. To save you time of finding the correct version of each library, all required libraries can be found in tripal_ws_brapps/libraries directory. Move all libraries to your Tripal site's libraries directory - **your tripal site/sites/all/libraries/**.

5. Enable the module tripal_ws_brapps.

- If this module is being tested on a base Tripal site: A test studies and traits, shown by the example charts above, are provided by enabling the module tripal_ws_brapi_testdata. Load data by accessing **your tripal site/tripalwsbrapi/testdata** page after enabling the testdata module.

- If this module is being tested on a KPClone: Studies and traits data will be provided by chado.phenotypes and chado.phenotypesprop tables.

6. Graphical Filtering can be accessed in this url:
**your tripal site/brapps/graphical-filtering**

- Note: when testing in KPClone - a study may take a while to load, it might appear it stopped working but just give it a little more time to render.

7. Study Comparison can be accessed in this url:
**your tripal site/brapps/study-comparison**

- Note when testing in KPClone - Of the 4 studies available, only two studies, listed below, share a common variable thus only these two can be used for testing.

- Studies for testing:

1. AGILE Activit 2....
2. Strategic Identification of New ....

- Once again, It may take a while to load, but jut give it a little more time to complete.

**Both BRAPPS can be tested on a live KP clone:**
.../fresh/brapps/graphical-filtering
.../fresh/brapps/study-comparison

### **How to use:**
1. Graphical Filtering. 
image

> 1. Choose a Study.
> 2. Click **Load** button.
> 3. Wait to render result.

2. Study Comparison
image

> 1. Choose Studies.
> 2. Click **Load Vars** button to examine studies selected for shared or common variables.
> 3. When studies have shared variable, it will become an option in the variables field. Choose one.
> 4. Click **Compare Variable** button.
> 5. Wait to render result.

**Comment by laceysanderson** [comment]
Reynold, the tests are failing because you still have `dpm()`s in your code...

**Review by laceysanderson — COMMENTED** [review]
Comments from testing on a KP Clone. I also tested on a base Tripal site and everything was as expected 👍 

## brapps/graphical-filtering
- Loads, working as designed :-)
- If you select 2+ studies, the alert box lets you know you shouldn’t… but it would make more sense to just radio buttons in the drop-down not checkboxes. It also feels weird + error-prone to have to press load once I select a study… and unnecessary since I can only select one anyway.
- The data list in the table is weird. 
  - There needs to be rounding decimal places for quantitive data (2 decimal places is pretty standard). 
  - For qualitative data (e.g. lodging) multiple data points should not be averaged but instead collated (e.g. if a specific germplasm has lodging values of 1,2,2,3,1,1 then you would want to show 1/2/3). 
  - Even though qualitative may be numbers (not always though) you cannot treat them as numbers (i.e. in the above example it is wrong to say 1-3). 
  - Can all this be controlled at the web service level without changing the Brapp?
- It would be good to have a drupal warning at the top for long loading studies. Since you say the Brapi call is fast, what about our own javascript that does a quick count of the number of records and if over a threshold adds a message letting the user know that this study may take a while to load?

## brapps/study-comparison
- Loads, working as designed.
- No comments on KP-based experience other than that I can’t wait until we have more data!

## Code review

- Took a quick look and everything looked good and as expected. :-)

**Comment by reynoldtan** [comment]
In addition - create help page for each tool

**Comment by reynoldtan** [comment]
**Added:**
1. Warning about some studies taking a while to load
2. Rounded off quantitative values to 2 decimal places.
3. Enumerated values of traits measuring scale (Not averaged)
4. Fixed qualitative values rendered as 0 (no shows the value ie: cotyledon color - Red or Yellow etc.)
5. GF uses radios, a better solution to indicate 1 selection at a time.

2, 3 and 4 were done in the core brapps script. please see
https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/pull/68/commits/3483a2feeb3670fcd38ef552070df495a53d5d24#diff-33f02a97076a274b916e8f83d5697e4c97c90736a81a0dbb95c25f4949ea6726

**Modified:**
1. I dropped the Unit column and placed the unit with the trait name. It was really confusing when unit was in its own column as it cannot be ascertained to which trait in the headers it corresponds to. This was achieve on the implementation script not on the brapps.
image


**Help page:**
1. I have also prepared the help content for both brapps in this docs file for Roubin.
[Help - brapps GF and SC.docx](https://github.com/UofS-Pulse-Binfo/tripal_ws_brapi/files/7427890/Help.-.brapps.GF.and.SC.docx)

**Review by laceysanderson — COMMENTED** [review]
Review for:
 - Warning about some studies taking a while to load: added warning works
 - Rounded off quantitative values to 2 decimal places.
 - Enumerated values of traits measuring scale (Not averaged)
 - Fixed qualitative values rendered as 0 (no shows the value ie: cotyledon color - Red or Yellow etc.)
 - GF uses radios, a better solution to indicate 1 selection at a time.

These all look good 👍 

## Clean-up

My main concern now is the inclusion of other libraries in our code base -especially now that there are alterations... 

We should move the graphical filtering and study comparison code from Breedbase (currently in includes directory) into the Drupal libraries folder and alter our module accordingly.

Regarding the changes to their core code, we need to 
1. Fork their repository
2. Make one branch per change (2, 3, 4) for a total of three branches so we can work towards contributing them back. 
3. We can then merge all three branches into a fourth branch (i.e. `uofs-master`) which we will use for KnowPulse and this module.

We also need to remove the libraries folder in the brapps module. While this makes install easier it is not ideal for attribution and maintenance.

**Comment by reynoldtan** [comment]
GRAPHICAL FILTERING UPDATES:
DataTable drawCallback to apply the following formatting to summary table data
1. Round off quantitative values to 2 decimal places.
2. Values sometimes cannot be averaged specially those with NA and so it displays 12/22/33/N/A
3. Qualitative values show text values and if multiple values will be separated by forward slash / ie Red/Yellow
4. Scale values will be sorted and enumerated using forward slash / as the separator ie 1/2/4/5 - Scale (1-5)

Tested:
1. Rounding off ✔️ 
2. Scale values ✔️ 
3. Qualitative values ✔️ 
4. Sorting by column headers ✔️ 
5. Disabled sort options in some headers ✔️ 
6. Search field ✔️ 
7. Number of entries/rows ✔️ 
8. Pagination ✔️  

Note:
1. Traits that contain qualitative values cannot be sorted thus sorting option is disabled

**Review by laceysanderson — COMMENTED** [review]
Code review looks perfect! Love all the comments in the JS code <3 
Just going to do a quick functional test now

**Comment by laceysanderson** [comment]
Awesome! Thanks @reynoldtan

**Pull request merged**
